import {
    Camera,
    Edit3,
    MapPin,
    Calendar,
    MessageSquare,
    Reply,
    Star,
    Plus,
    Mail,
    Bell,
    ExternalLink,
    User,
    Hash,
    Users,
    HelpCircle,
    Lightbulb,
    Code,
    Clock,
    SearchIcon,
    Send,
    Briefcase,
    Shield,
    Twitter,
    Github,
    BookOpen,
    Target,
    Heart,
    Globe,
    Coffee,
    TrendingUp,
    FileText,
    Video,
    Phone,
    Book,
    Menu,
    Home
} from "lucide-react";

import GoogleIcon from "./custom/Google";
import LogoIcon from "./custom/Logo";

export const Icons = {
    Home: Home, 
    Camera: Camera,
    Edit: Edit3,
    MapPin: MapPin,
    Calendar: Calendar,
    MessageSquare: MessageSquare,
    Reply: Reply,
    Star: Star,
    Plus: Plus,
    Mail: Mail,
    Bell: Bell,
    ExternalLink: ExternalLink,
    User: User,
    Hash: Hash,
    Users: Users,
    HelpCircle: HelpCircle,
    Lightbulb: Lightbulb,
    Code: Code,
    Clock: Clock,
    Search: SearchIcon,
    Send: Send,
    Briefcase: Briefcase,
    Shield: Shield,
    Twitter: Twitter,
    Github: Github,
    Book: Book,
    BookOpen: BookOpen,
    Target: Target,
    Heart: Heart,
    Globe: Globe,
    Coffee: Coffee,
    TrendingUp: TrendingUp,
    FileText: FileText,
    Video: Video,
    Phone: Phone,
    Menu: Menu,
    Google: GoogleIcon,
    Logo: LogoIcon,
};